export const GET_CHAPTERS = "GET_CHAPTERS";
export const SET_CHAPTERS = "SET_CHAPTERS";
export const GET_CHAPTER = "GET_CHAPTER";
export const SET_CHAPTER_FAV_STATUS = "SET_CHAPTHER_FAV_STATUS";


export const GET_VERSES = "GET_VERSES";
export const GET_VERSE = "GET_VERSE";
export const SET_VERSES = "SET_VERSES";
export const CLEAN_VERSES = "CLEAN_VERSES";
export const SET_VERSE_FAV_STATUS = "SET_VERSE_FAV_STATUS";